---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
components:
  - ../../../infra/namespace

resources:
  - ./monitoring/ks.yaml
  - ./limit-ranges/ks.yaml
  - ./resource-quotas/ks.yaml
  - ./network-policies/ks.yaml
