---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
# DISABLED: Changed from namespace (istio-enabled) to namespace-privileged
# to disable Istio ambient mode for easier development
components:
  - ../../../infra/namespace-privileged

resources:
  - ./monitoring/ks.yaml
  - ./limit-ranges/ks.yaml
  - ./resource-quotas/ks.yaml
  - ./flux-operator-web/ks.yaml
  # DISABLED: Commented out for easier development/deployment
  # - ./network-policies/ks.yaml
