---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./alertmanager.yaml
  - ./cloudflare-tunnel.yaml
  - ./prometheus.yaml
  - ./kube-state-metrics.yaml
  - ./ocirepository.yaml 
  - ./node-exporter.yaml

