---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
components:
  - ../../../infra/namespace-privileged

resources:
  - ./flux-alerts/ks.yaml
  - ./grafana/ks.yaml
  - ./kube-prometheus-stack/ks.yaml
  - ./open-telemetry/ks.yaml
  - ./limit-range-override
  - ./resource-quota-override
  - ./network-policies/ks.yaml
  - ./seaweedfs/ks.yaml
