---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
components:
  - ../../../infra/namespace

resources:
  - ./cluster-secrets/ks.yaml
  - ./kube-prometheus-stack/ks.yaml
  - ./grafana/ks.yaml
  - ./flux-alerts/ks.yaml

patches:
  - patch: |-
      - op: remove
        path: /metadata/labels/istio-injection
    target:
      kind: Namespace
      name: monitoring
