---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
components:
  - ../../../infra/namespace

resources:
  - ./cluster-secrets/ks.yaml
  - ./prometheus-community/ks.yaml
  - ./grafana/ks.yaml
  - ./flux-dashboards/ks.yaml
