---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./kube-prometheus-stack.yaml
  - ./ocirepository.yaml
configMapGenerator:
  - name: flux-kube-state-metrics-config
    files:
      - kube-state-metrics-config.yaml
    options:
      labels:
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: monitoring
  - name: flux-cluster-dashboard
    files:
      - dashboards/flux-cluster.json
    options:
      labels:
        grafana_dashboard: "1"
  - name: flux-control-plane-dashboard
    files:
      - dashboards/flux-control-plane.json
    options:
      labels:
        grafana_dashboard: "1"
  - name: flux-logs-dashboard
    files:
      - dashboards/flux-logs.json
    options:
      labels:
        grafana_dashboard: "1"
configurations:
  - kustomizeconfig.yaml