---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authentik
# DISABLED: Changed from namespace-istio-enabled to namespace-privileged
# to disable Istio ambient mode for easier development
components:
  - ../../../infra/namespace-privileged

resources:
  - ./secrets/ks.yaml
  - ./operator/ks.yaml
  - ./limit-ranges/ks.yaml
  - ./resource-quotas/ks.yaml
  # DISABLED: Commented out for easier development/deployment
  # - ./network-policies/ks.yaml

