---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-ops
components:
  - ../../../infra/namespace-privileged

resources:
  - ./cert-manager/ks.yaml
  - ./external-secrets/ks.yaml
  - ./local-path-provisioner/ks.yaml
  - ./metal-lb/ks.yaml
