---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-ops
components:
  - ../../../infra/namespace-privileged

resources:
  - ./cert-manager/operator/ks.yaml
  - ./cert-manager/selfsigned/ks.yaml
  - ./cert-manager/certificates/ks.yaml
  - ./cert-manager/letsencrypt/ks.yaml
  - ./external-secrets/operator/ks.yaml
  - ./external-secrets/store/ks.yaml
  - ./metal-lb/operator/ks.yaml
  - ./metal-lb/resources/ks.yaml
  - ./limit-ranges/ks.yaml
  - ./resource-quotas/ks.yaml
  - ./network-policies/ks.yaml
