apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: s3-credentials
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: s3-credentials
  data:
  - secretKey: AWS_ACCESS_KEY_ID
    remoteRef:
      key: "bb4663e0-bd91-4051-8ce2-b3ca0011e145"
  - secretKey: AWS_SECRET_ACCESS_KEY
    remoteRef:
      key: "64cca494-0538-4cfb-a13e-b3cb01751b3e"