---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./youtube-mcp.yaml
  - ./anthropic1.yaml
  - ./anthropic2.yaml
  - ./anthropic3.yaml

