---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metrics-server
components:
  - ../../../infra/namespace-privileged

resources:
  - ./ks.yaml
