---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kgateway
components:
  - ../../../infra/namespace-istio-enabled

resources:
  - ./ks.yaml

