---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-system
components:
  - ../../../infra/namespace-privileged

resources:
  - ./operator/ks.yaml
  - ./limit-ranges/ks.yaml
  - ./resource-quotas/ks.yaml
  - ./network-policies/ks.yaml
