---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./blog-agent.yaml
  - ./youtube-agent.yaml
  - ./renovate-list-agent.yaml
  - ./renovate-review-agent.yaml
  - ./renovate-revert-agent.yaml
  - ./flux-health-agent.yaml
