---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./agentgateway-parameters.yaml
  - ./agentgateway.yaml
  - ./deployment.yaml
  - ./configmap.yaml
  - ./service.yaml
