---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kgateway-system
components:
  - ../../../infra/namespace-istio-enabled

resources:
  - ./crds/ks.yaml
  - ./operator/ks.yaml
  - ./limit-ranges/ks.yaml
  - ./resource-quotas/ks.yaml
  - ./network-policies/ks.yaml
  - ./gateway/ks.yaml
  - ./gatewayparameters/ks.yaml
  - ./httplistenerspolicy/ks.yaml
  - ./backends/ks.yaml
  - ./httproute/ks.yaml
  - ./certificate/ks.yaml
  - ./referencegrants/ks.yaml
  - ./observability/ks.yaml