---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kgateway-system
# DISABLED: Changed from namespace-istio-enabled to namespace-privileged
# to disable Istio ambient mode for easier development
components:
  - ../../../infra/namespace-privileged

resources:
  - ./crds/ks.yaml
  - ./operator/ks.yaml
  - ./limit-ranges/ks.yaml
  - ./resource-quotas/ks.yaml
  # DISABLED: Commented out for easier development/deployment
  # - ./network-policies/ks.yaml
  - ./gateway/ks.yaml
  - ./agentgatewayparameters/ks.yaml
  - ./agentgatewaypolicy/ks.yaml
  - ./backends/ks.yaml
  - ./httproute/ks.yaml
  - ./certificate/ks.yaml
  - ./referencegrants/ks.yaml
  - ./peerauthentication/ks.yaml
  - ./observability/ks.yaml
  - ./dashboards/ks.yaml
  - ./secrets/ks.yaml