---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kgateway
resources:
  - otel-collector/otel-collector.yaml
  - servicemonitors/kgateway-servicemonitors.yaml
  - dashboards
