---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../../infra/namespace-istio-enabled

resources:
  - ./operator/ks.yaml
  - ./cluster/ks.yaml
