---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kagent
components:
  - ../../../infra/namespace-istio-privileged

resources:
  - ./crds/ks.yaml
  - ./operator/ks.yaml
  - ./limit-ranges/ks.yaml
  - ./resource-quotas/ks.yaml
  - ./network-policies/ks.yaml
  - ./secrets/ks.yaml
  - ./oauth2-proxy/ks.yaml
  - ./providers/ks.yaml
  - ./mcps/ks.yaml
  - ./agents/ks.yaml
