---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: n8n
components:
  - ../../../infra/namespace

resources:
  - ./secrets/ks.yaml
  - ./app/ks.yaml
  - ./limit-ranges/ks.yaml
  - ./resource-quotas/ks.yaml
