---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
components:
  - ../../../infra/namespace-istio-privileged

resources:
  - ./istio/operator/ks.yaml
  - ./istio/gateway/ks.yaml
  - ./istio/security/ks.yaml
  - ./istio/tunnels/ks.yaml
  - ./istio/secrets/ks.yaml
  - ./istio/httproutes/ks.yaml
  - ./istio/referencegrants/ks.yaml
  - ./network-policies/ks.yaml
  - ./kiali/operator/ks.yaml
  - ./kiali/secrets/ks.yaml
  - ./kiali/cr/ks.yaml