---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
  - ./a2a.yaml
  - ./gateway.yaml
  - ./backends.yaml
  - ./httproute.yaml

patches:
  - path: istio-port-exclusions.yaml
    target:
      kind: Deployment
      name: agentgateway